services:
  database:
    container_name: sistema-ponto-database
    image: postgres:18-alpine

    # env_file:
    #   - ../.env.development

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sistema_ponto

    ports:
      - "5432:5432"

    # esse 'volumes' faz com que os dados n sejam perdidosquando o container reincniar
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
